spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

langchain4j.open-ai.streaming-chat-model.log-requests=false
langchain4j.open-ai.streaming-chat-model.log-responses=false

logging.level.com.tetranyble.ailearn=INFO

logging.level.root=INFO
logging.structured.format.console=logstash
app.chat.websocket.allowed-origin-patterns=${CHAT_WEBSOCKET_ALLOWED_ORIGIN_PATTERNS}
