spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=true

langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

logging.level.com.tetranyble.ailearn=DEBUG
logging.level.org.hibernate.SQL=${HIBERNATE_SQL_LOG_LEVEL:INFO}
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level [requestId=%X{requestId:-none}] %logger{36} - %msg%n
